function Bsym = Bsymfun(in1,uCMG)
%BSYMFUN
%    BSYM = BSYMFUN(IN1,UCMG)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    15-Jul-2021 10:47:26

th1 = in1(1,:);
th2 = in1(2,:);
t2 = -th2;
t3 = t2+th1;
t4 = cos(t3);
t5 = t4.^2;
t6 = t5.*3.501823623940783e+36;
t7 = t6-2.184958382060512e+37;
t8 = 1.0./t7;
Bsym = [0.0;0.0;t4.*t8.*-1.316821578588645e+36;t8.*-2.865645210612444e+37];
